### ISSUE TITLE
sharelatex doesn't run as per the instructions

### ISSUE THREAD

**Issue by muelli** [palkan/sharelatex-vagrant-ansible#9]
The readme says to run "grunt" in "/webapps/sharelatex".
But that doesn't work for me:

```
vagrant@precise64:~$ cd /webapps/sharelatex
vagrant@precise64:/webapps/sharelatex$ grunt run
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
vagrant@precise64:/webapps/sharelatex$ ls
vagrant@precise64:/webapps/sharelatex$ 
```

So either the ansible playbook is not really describing the necessary state or the instructions are incomplete.

**Comment by palkan** [comment]
Try `vagrant provision` again, it looks like it has failed.

**Comment by muelli** [comment]
ansible runs fine.

```
>vagrant provision
==> default: Configuring proxy for Apt...
==> default: Configuring proxy environment variables...
==> default: Configuring proxy for npm...
==> default: Running provisioner: vai...
==> default: Inventory sucessfully written to priv/ansible/vagrant_ansible_inventory
==> default: Configuring proxy for npm...
==> default: Running provisioner: ansible...

PLAY [development] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [192.168.51.111]

TASK: [common | upgrade] ****************************************************** 
ok: [192.168.51.111]

TASK: [common | ensure the system encoding is utf-8] ************************** 
ok: [192.168.51.111]

TASK: [common | install packages] ********************************************* 
ok: [192.168.51.111] => (item=build-essential,automake,bison,autoconf,pkg-config,libreadline6,libreadline6-dev,openssl,libssl-dev,curl,git,zlib1g,zlib1g-dev,libyaml-dev,libsqlite3-dev,libxml2-dev,libxslt1-dev,curl,nfs-common,vim)

TASK: [mongo | Add 10gen key] ************************************************* 
ok: [192.168.51.111]

TASK: [mongo | Copy 10gen.list to /etc/apt/sources.list.d] ******************** 
ok: [192.168.51.111]

TASK: [mongo | Make sure 10gen.list is present] ******************************* 
ok: [192.168.51.111]

TASK: [mongo | Update apt-cache] ********************************************** 
ok: [192.168.51.111]

TASK: [mongo | Install MongoDB] *********************************************** 
ok: [192.168.51.111]

TASK: [mongo | Make sure MongoDB is running] ********************************** 
ok: [192.168.51.111]

TASK: [redis | Checking installed version of redis] *************************** 
changed: [192.168.51.111]

TASK: [redis | Purge previous] ************************************************ 
skipping: [192.168.51.111]

TASK: [redis | Download Redis] ************************************************ 
skipping: [192.168.51.111]

TASK: [redis | Untar Redis] *************************************************** 
skipping: [192.168.51.111]

TASK: [redis | Install Redis] ************************************************* 
skipping: [192.168.51.111]

TASK: [redis | Create user redis] ********************************************* 
skipping: [192.168.51.111]

TASK: [redis | Configure Upstart for Redis] *********************************** 
ok: [192.168.51.111]

TASK: [redis | Start Redis] *************************************************** 
ok: [192.168.51.111]

TASK: [nodejs | Checking installed version of node.js] ************************ 
changed: [192.168.51.111]

TASK: [nodejs | Purge previous] *********************************************** 
skipping: [192.168.51.111]

TASK: [nodejs | Fetching node.js source] ************************************** 
skipping: [192.168.51.111]

TASK: [nodejs | Unpack node.js tarball] *************************************** 
skipping: [192.168.51.111]

TASK: [nodejs | Configure] **************************************************** 
skipping: [192.168.51.111]

TASK: [nodejs | Make] ********************************************************* 
skipping: [192.168.51.111]

TASK: [nodejs | Make install] ************************************************* 
skipping: [192.168.51.111]

TASK: [nodejs | Install npm] ************************************************** 
ok: [192.168.51.111]

TASK: [texlive | Install TexLive] ********************************************* 
ok: [192.168.51.111]

TASK: [texlive | Download latexmk] ******************************************** 
ok: [192.168.51.111]

TASK: [texlive | Update permissions] ****************************************** 
changed: [192.168.51.111]

TASK: [sharelatex | Install Grunt.js package globally.] *********************** 
ok: [192.168.51.111]

TASK: [sharelatex | Install node-gyp globally] ******************************** 
ok: [192.168.51.111]

TASK: [sharelatex | Git Checkout ShareLatex master] *************************** 
changed: [192.168.51.111]

TASK: [sharelatex | Setup config] ********************************************* 
changed: [192.168.51.111]

TASK: [sharelatex | NPM update via package.json] ****************************** 
changed: [192.168.51.111]

TASK: [sharelatex | Grunt install] ******************************************** 
changed: [192.168.51.111]

TASK: [sharelatex | Grunt check] ********************************************** 
changed: [192.168.51.111]

PLAY RECAP ******************************************************************** 
192.168.51.111             : ok=25   changed=8    unreachable=0    failed=0   

==> default: Configuring proxy for npm...

```

**Comment by muelli** [comment]
ah. now it works a little better. weird.

```
Running "execute:chat" (execute) task
-> executing /webapps/sharelatex/chat/app.js

module.js:340

module.js:340
    throw err;
          ^
Error: Cannot find module 'logger-sharelatex'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/webapps/sharelatex/docstore/app.js:6:12)
    at Object.<anonymous> (/webapps/sharelatex/docstore/app.js:76:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
    throw err;
          ^
Warning: -> error 8 /webapps/sharelatex/docstore/app.js (1305ms) Use --force to continue.

Aborted due to warnings.
Error: Cannot find module 'logger-sharelatex'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/webapps/sharelatex/track-changes/app.js:6:12)
    at Object.<anonymous> (/webapps/sharelatex/track-changes/app.js:84:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
Warning: -> error 8 /webapps/sharelatex/track-changes/app.js (1295ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

        Aborted due to warnings.
```

**Comment by palkan** [comment]
It looks like [this one](https://github.com/palkan/sharelatex-vagrant-ansible/issues/6).

**Comment by muelli** [comment]
hm. I think this error here "Error: Cannot find module 'logger-sharelatex'" looks different.

It seems that grunt install is having problems:

```
> bcrypt@0.8.3 install /webapps/sharelatex/web/node_modules/bcrypt
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES, unlink 'build'
gyp ERR! System Linux 3.2.0-89-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /webapps/sharelatex/web/node_modules/bcrypt
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-89-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! cwd /webapps/sharelatex/web
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /webapps/sharelatex/web/npm-debug.log
npm ERR! not ok code 0
Running "clean:app" (clean) task
Cleaning app/js...OK
```

it still exists with exit code 0, though.
